---
fixtures:
  repositories:
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    alternatives: 'https://github.com/voxpupuli/puppet-alternatives.git'
    apt: 'https://github.com/puppetlabs/puppetlabs-apt.git'
    yumrepo_core: 'https://github.com/puppetlabs/puppetlabs-yumrepo_core.git'
...
