---
fixtures:
  repositories:
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    alternatives: 'git://github.com/voxpupuli/puppet-alternatives.git'
    apt: 'git://github.com/puppetlabs/puppetlabs-apt.git'
...
